### ISSUE TITLE
可以实现底部加载更多么？

### ISSUE THREAD

**Issue by csh159** [linxin6560/DetailScrollView#3]

**Comment by linxin6560** [comment]
加载更多正常情况下，listview或者recyclerview怎么做，就怎么做呗。与这个控件无关

**Comment by SiberiaDante** [comment]
像smartRefreshLayout这种框架，应该如何使用呢，包裹RecyclerView会保存；报错整个布局的外层，刷新事件确拿不到，有什么方法能解决嘛
