### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by babaybusandroid** [linxin6560/DetailScrollView#4]
下滑的时候会webview的滑动惯性会传递到listview，但是listview上滑的关系没办法传递给webview，能不能支持

**Comment by linxin6560** [comment]
我们这边的需求是照抄今日头条的。所以我就没处理ListView到WebView的过渡。

**Comment by JustRight815** [comment]
现在今日头条的也是listview上滑到webview惯性滑动的了

**Comment by linxin6560** [comment]
已完善
