### ISSUE TITLE
从ListView往上滑动的时候到Webview的时候会卡主，WebView内容不满一屏幕会留下一大片空白

### ISSUE THREAD

**Issue by mtoday** [linxin6560/DetailScrollView#5]
从ListView往上滑动的时候到Webview的时候会卡主，WebView内容不满一屏幕会留下一大片空白

**Comment by linxin6560** [comment]
1.我们这边的需求是照抄今日头条的。所以我就没处理ListView到WebView的过渡。
2.DetailWebView的高度设置成wrap_content应该就行了，但是这样子会有个问题，前端H5的代码的高度不能用100%，得用固定的高度

**Comment by mtoday** [comment]
从ListView往上滑动的时候到Webview的时候会卡主这个过渡能提供思路吗？

**Comment by JustRight815** [comment]
可以在ListView 的overScrollBy方法中判断是否滑到了边界，然后计算到到达边界时的加速度，让scroollview按这个加速度继续滚动。我花了半天时间实现了这个效果

**Comment by linxin6560** [comment]
已完善
